name: cfclone
channels:
  - conda-forge
dependencies:
  - python>=3.12
  - click>=8.0
  - cxx-compiler
  - juliaup
  - make
  - numpy
  - pandas
  - tbb-devel
  - pyjuliacall
  - pyjuliapkg
#  - pip
#  - pip:
#      - juliacall
#      - juliapkg
