name: cfclone
channels:
  - conda-forge
dependencies:
  - python>=3.12
  - click>=8.0
  - cxx-compiler
  - h5py
  - arviz
  - juliaup
  - make
  - numpy
  - pandas
  - tbb-devel
  - pyjuliacall>=0.9.22
  - pyjuliapkg
